### ISSUE TITLE
Unable to download, report http403 error

### ISSUE THREAD

**Issue by if-endless** [gmberton/EarthLoc#4] opened 2024-10-11 07:25 UTC
Downloading DB:   0%|          | 0/161496 [00:00<?, ?it/s]Couldn't download https://s2maps-tiles.eu/wmts?layer=s2cloudless-2018_3857&style=default&tilematrixset=GoogleMapsCompatible&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=9&TileCol=196&TileRow=260 due to HTTP Error 403: Forbidden, will retry in 10 seconds
Couldn't download https://s2maps-tiles.eu/wmts?layer=s2cloudless-2018_3857&style=default&tilematrixset=GoogleMapsCompatible&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=9&TileCol=194&TileRow=260 due to HTTP Error 403: Forbidden, will retry in 10 seconds
Couldn't download https://s2maps-tiles.eu/wmts?layer=s2cloudless-2018_3857&style=default&tilematrixset=GoogleMapsCompatible&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=9&TileCol=198&TileRow=264 due to HTTP Error 403: Forbidden, will retry in 10 seconds

**Comment by gmberton** [comment] 2024-10-11 08:20
Duplicate of #3

**Closed as completed by gmberton** 2024-10-11 08:20 UTC

**Comment by gmberton** [comment] 2025-05-26 20:52
I have now uploaded the dataset to a server and it can be downloaded with
```
rsync -rhz --info=progress2 --ignore-existing rsync://vandaldata.polito.it/sf_xl/EarthLoc/data .
```

I've also updated the README to mirror the changes
